#!/bin/bash
ololo1=`loginctl --no-ask-password list-sessions | grep "seat" | awk '{print $1}' | tr '\n' ' '`
#loginctl --no-ask-password lock-session c2 c4
echo "lock"
loginctl --no-ask-password lock-session $ololo1
#loginctl --no-ask-password lock-session ${loginctl --no-ask-password list-sessions | grep "seat" | grep "admin" | awk '{print $1}'}